### Exercício número 4 da lista do canal CuroEmVídeo
algo1 = input('Digite algo:')
algo2 = input('Digite outro algo:')
print('A primeira coisa digitada é do tipo', type(algo1))
print('A segunda coisa digitada é do tipo', type(algo2))
print('É claro que será sting. Você sabe por quê?')
print('A primeira coisa digitada pode ser um núemro?', algo1.isnumeric())
print('A segunda coisa digitada pode ser um número?', algo2.isnumeric())
print('A primeira coisa digitada pode ser letra(s)?', algo1.isalpha())
print('A segunda coisa digitada pode ser letra(s)?', algo2.isalpha())
print('A primeira coisa digitada pode ser alfaNumerica?', algo1.isalnum())
print('A segunda coisa digitada pode ser alfaNumerica?', algo2.isalpha())
print('A primeira coisa é vazia?', algo1.isspace())
print('A segunda coisa é vazia?', algo2.isspace())
print('A primeira coisa está em maiúsculo?', algo1.isupper())
print('A segunda coisa está em maisúsculo?', algo2.isupper())
print('A primeira coisa está em minúsculo?', algo1.islower())
print('A segunda coisa está em minúsculo?', algo2.islower())
print('A primeira coisa está captalizada?', algo1.istitle())
print('A segunda coisa está captalizada?', algo2.istitle())
print('A primeira coisa pode ser float', algo1.isdecimal())
print('A segunda coisa pode ser float?', algo2.isdecimal())
print('A primeira coisa contém apenas números?', algo1.isdigit())
print('A segunda coisa contém apenas números?', algo2.isdigit())
print('A primeira coisa pode ser um identificador válido?', algo1.isidentifier())
print('A segunda coisa pode ser um identificador válido?', algo2.isidentifier())
print('A primeira coisa é imprimível?', algo1.isprintable())
print('A segunda coisa é imprimível?', algo2.isprintable()) #isto aprenas imprime
print('É uma versão imprimível a primeira coisa?', algo1.isascii())
print('É uma versão imprimpivel a segunda coisa?', algo2.isascii()) #isto retorna o que é imprimível transformando o que não é para o que é
